[package]
name = "ethbridge"
version = "0.1.0"
authors = ["Frederic Fortier <fredfortier@gmail.com>"]

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
rustc-hex = "1.0.0"
serde_json = "1.0"

[dev-dependencies]
mockers = "0.11.2"
mockers_derive = "0.11.2"

