kind: pipeline
name: default
steps:

  - name: integration
    image: enigmampc/docker-client
    privileged: true
    volumes:
      - name: sock
        path: /var/run/docker.sock
    commands:
      - git clone https://github.com/enigmampc/discovery-docker-network.git
      - cd discovery-docker-network && cp .env-template .env
      - sed -i "s/COMPOSE_PROJECT_NAME=.*/COMPOSE_PROJECT_NAME=enigma_${DRONE_BUILD_NUMBER}/" .env
      - export MATCHING_BRANCH_P2P="$(git ls-remote --heads https://github.com/enigmampc/enigma-p2p.git ${DRONE_BRANCH} | wc -l)"
      - export MATCHING_BRANCH_CONTRACT="$(git ls-remote --heads https://github.com/enigmampc/enigma-contract.git ${DRONE_BRANCH} | wc -l)"
      - export DOCKER_TAG=core_${DRONE_BUILD_NUMBER}
      - sed -i "s/DOCKER_TAG=latest/DOCKER_TAG=${DOCKER_TAG}/" .env;
      - /bin/bash --version
      - /bin/bash -c "
        declare -a PROJECTS=(p2p contract);
        declare -A DOCKER_IMAGES=([p2p]=enigma_p2p [contract]=enigma_contract);"
      
volumes:
  - name: isgx
    host:
      path: /dev/isgx
  - name: sock
    host:
      path: /var/run/docker.sock
