[package]

name = "enigma-worker-surface"
version = "0.1.0"
authors = ["enigma <support@enigma.co>"]
build = "build.rs"
description = "The so called untrusted part of the Enigma node."
keywords =["enigma","sgx","web3"]
categories=["api-bindings","cryptography","development-tools"]
repository="https://github.com/enigmampc/enigma-core.git"
license="non-standard"

[dependencies]
base64 = "0.9.1"
libc = "0.2.41"
zmq = "0.8.2"
serde_json = "1.0"
serde = "1.0.66"
serde_derive = "1.0.66"
failure = "=0.1.1"
failure_derive="=0.1.1"
rustc-hex = "1.0.0"
httparse = "=1.2.5"
reqwest = "0.8.6"
dirs = "1.0"
enigma-tools-u = "0.1.2"
sgx_types = "1.0.0"
sgx_urts="1.0.0"

