[package]
name = "enigma-tools-u"
version = "0.1.0"
authors = ["Isan-Rivkin <isanrivkin@gmail.com>"]
description = "Tools used by the untrusted part of the Enigma core and Principal node."
build = "build.rs"
keywords =["enigma","sgx","web3"]
categories=["api-bindings","cryptography","development-tools"]
repository="https://github.com/enigmampc/enigma-core.git"
documentation="https://enigma.co/protocol/"
license="MIT"
[dependencies]
serde_json = "1.0"
serde = "1.0.66"
serde_derive = "1.0.66"
failure = "=0.1.1"
failure_derive="=0.1.1"
httparse = "=1.2.5"
reqwest = "0.8.6"
etcommon-rlp = "0.2.3"
base64 = "0.9.2"
openssl = "0.10.10"
rustc-hex = "1.0.0"
# web3 utils
web3 = "0.3.1"
libc = "0.2.41"
tiny-keccak = "1.4.2"
#sgx
sgx_types="1.0.0"
sgx_urts="1.0.0"
